version: "3.11"

services:
  app:
    build: .
    container_name: rad-ai-routing-app
    restart: unless-stopped
    expose:
      - "8501"

  nginx:
    image: nginx:1.25-alpine
    container_name: rad-ai-routing-proxy
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./deployment/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
